#!/bin/sh /etc/rc.common
START=90
STOP=90

NAME=pdnsd
SSNAME=easucks
DESC="proxy DNS server"

DAEMON=/usr/sbin/pdnsd
PIDFILE=/var/run/$NAME.pid
CACHEDIR=/var/cache/pdnsd
CACHE=$CACHEDIR/pdnsd.cache
CONFIG_FILE=/etc/pdnsd.conf

USER=nobody
GROUP=nogroup

start() {
    echo "Starting $DESC: $NAME"
    ss_server_choice=$(uci get $SSNAME.ss_server_choice)
    ss_remote_dnss=$(uci get $SSNAME.$ss_server_choice.ss_remote_dnss)
    cat > $CONFIG_FILE <<EOF
global {
    perm_cache      = 65535;
    cache_dir       = $CACHEDIR;
    status_ctl      = on;
    server_ip       = 127.0.0.1;
    server_port     = 54;
    query_method    = tcp_only;
    tcp_server      = off;
    min_ttl         = 1d;
    max_ttl         = 1w;
    timeout         = 10;
    randomize_recs  = on;
    debug           = off;
    daemon          = on;
    verbosity       = 1;
    neg_rrs_pol     = on;
    neg_domain_pol  = on;
    par_queries     = 1;
}

server {
    label = "ss_remote_ddns";
    ip=$ss_remote_dnss;
    proxy_only = on;
    timeout = 5;
    caching = on;
    purge_cache = off;
}
EOF
    gen_cache
    $DAEMON --daemon -p $PIDFILE
    chmod 644 $CONFIG_FILE
}

stop() {
   echo "Stopping $DESC: $NAME"
   kill `cat $PIDFILE 2>/dev/null` 2>/dev/null
   killall $DAEMON 2>/dev/null
   rm -f $PIDFILE
   rm -f $CONFIG_FILE
}

restart() {
   echo "Restarting $DESC: $NAME... "
   stop
   sleep 2
   start
}

gen_cache()
{
   if ! test -f "$CACHE"; then
       mkdir -p `dirname $CACHE`
       dd if=/dev/zero of="$CACHE" bs=1 count=4 2> /dev/null
       chown -R $USER.$GROUP $CACHEDIR
   fi
}
